### PR TITLE
Enable nullable reference types

### PR DESCRIPTION
**Pull request by 0xced**
Annotate all potentially nullable reference types accordingly

### CODE REVIEW

**Review by martincostello — APPROVED** [review]
This looks great - thanks @0xced!

**Comment by martincostello** [comment]
@0xced Would you mind trying out the prerelease build from MyGet with your change in your project(s) and check you're happy with the changes? If so, I'll push 0.1.2 to NuGet.org.

https://www.myget.org/feed/martincostello/package/nuget/MartinCostello.Logging.XUnit/0.1.2-beta0206

**Comment by 0xced** [comment]
Actually, I'm not using this package, yet! I was planing another pull requests (support for [`IMessageSink`](https://github.com/xunit/xunit/pull/1705) in additino to `ITestOutputHelper`) and I thought it was safer to enable null reference types first. 😉

**Comment by martincostello** [comment]
Ah nice. In that case (unless it's going to be a _very_ long time), I'll wait for that and the changes can go together 🙂

**Pull request merged**
