### PR TITLE
Broken gh logger

### PR DESCRIPTION
**Pull request by nohwnd**
Trying for issue https://github.com/dotnet/sdk/issues/41299

### CODE REVIEW

**Comment by nohwnd** [comment]
https://github.com/nohwnd/terminal-logger-gh/actions/runs/9383838282?pr=1 it seems to work on mine with preview5, in fact the macos output is the nicest :D I think there was also a bug in sdk where macos tests crashed on xunit , this one https://github.com/dotnet/sdk/issues/40194 so maybe  we are hitting the crash here on macos. But the lack of output is preventing us from seeing it. I've made an issue on msbuild here to print all the info that reaches console, instead of just the well known messages (Well known to Terminal logger).  https://github.com/dotnet/msbuild/pull/10203

**Comment by martincostello** [comment]
Interesting - that might overlap with this issue (a crash on macOS) I've been getting, which is kinda what lead me back to https://github.com/dotnet/sdk/issues/41299 in the first place: https://github.com/dotnet/runtime/issues/102313

**Comment by martincostello** [comment]
Approving the workflow run here, looks like it's still repro'ing (and the lack of information has switched from macOS to Windows)

**Comment by nohwnd** [comment]
To me it looks more like .net installation issue. In the windows output it lists the .net runtimes and it does not have the preview5. and it finds it in program files, not in your private installation that comes from setup-dotnet.  Pushed more changes to add dotnet_root, just to see if that will take us one step further. 

 9.0.0-preview.4.24266.19  is the runtime that is linked to the official preview4 SDK, so it worked for you before when you used 9.0.100-preview.4.24267.66, because you installed that via setup-dotnet to private installation and there already was a respective runtime on the agent. (at least that is my educated guess why we see it fail now and not before)
 
image

**Comment by nohwnd** [comment]
after dotnet_root we can see result on windows, but not on macos / linux, disabling terminal logger, let's see what it wanted to print, thanks for your patience 😁

**Comment by nohwnd** [comment]
got it, when you set DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1 (you do that in build.yaml), it will output `` `e[39;49m `` one or two times before the message, (default color + reset), and this breaks our simple text based protocol, because we then don't recognize the messages.

**Pull request closed without merging**
